# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://blog.qiang.uk/"
title: 远望世界
copyright: "© 2025 [远望世界](https://github.com/yuanwangshijie)"
paginate: 5
theme: [hugo-PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts"]
defaultContentLanguage: "zh"
hasCJKLanguage: true # 是否包括中日韩文字

permalinks:
  posts: "/:year/:month/:day/:title/"

minify:
  disableXML: true
  # minifyOutput: true

languages:
  zh:
    languageName: "简体中文"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 归档
          url: archives
          weight: 1
        - name: 搜索
          url: search
          weight: 2
        - name: 标签
          url: tags
          weight: 3
        - name: 分类
          url: categories
          weight: 4
        - name: 随记
          url: https://memo.qiang.uk/
          weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable Google Analytics, opengraph, twitter-cards and schema.
  description: ""
  author: 远望世界
  DateFormat: "2006-01-02"
  # author: ["Me", "You"] # multiple authors
  defaultTheme: dark
  # disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true # 是否显示上一篇和下一篇
  ShowBreadCrumbs: false # 是否显示面包屑
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowFullTextinRSS: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true # 是否显示目录
  # comments: true
  images: ["/icons/avatar.png"]

  profileMode:
    enabled: false
    title: 远望世界
    imageUrl: "/icons/avatar.png"
    imageTitle: 远望世界
    # imageWidth: 120
    # imageHeight: 120
    buttons:
      - name: 文章
        url: posts
      - name: 随记
        url: https://memo.qiang.uk/

  # 主页样式 post-entry.css 和 zmedia.css
  homeInfoParams:
    Title: "自由在高处"
    Content:

  socialIcons:
    - name: github
      url: "https://github.com/yuanwangshijie"
    - name: email
      url: "mailto:yuanwangshijie@gmail.com"
    - name: rss
      url: "https://blog.qiang.uk/index.xml"

  editPost:
    URL: "https://github.com/yuanwangshijie/hugo-blog/tree/main/content"
    Text: "编辑此页" # edit text
    appendFilePath: true # to append file path to Edit link

  #  label:
  #    iconSVG: ''
  #    text: "远望世界"
  #    icon: ""
  #    iconHeight: 35

  #  analytics:
  #    google:
  #      SiteVerificationTag: "XYZabc"

  assets:
    disableHLJS: true
    favicon: "/icons/favicon.ico"
    favicon16x16: "/icons/favicon-16x16.png"
    favicon32x32: "/icons/favicon-32x32.png"
    apple_touch_icon: "/icons/apple-touch-icon.png"
    safari_pinned_tab: "/icons/safari-pinned-tab.svg"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
